pr: none
trigger:
  tags:
    include:
      - '*'

variables:
- group: ConqueryConstants

pool:
  vmImage: $(IMAGE)
steps:
- bash: |
    echo "setting TAG= ${$(Build.SourceBranch):11}"
    echo "##vso[task.setvariable variable=TAG]${$(Build.SourceBranch):11}"
- task: Maven@3
  displayName: set version
  inputs:
    jdkVersionOption: '1.11'
    goals: initialize
    options: $(MVN) -P setEvaVersion
- task: Maven@3
  displayName: build conquery
  inputs:
    jdkVersionOption: '1.11'
    options: $(MVN) -T 1C -DskipTests
- task: GitHubRelease@0
  displayName: create prerelease
  inputs:
    gitHubConnection: bot
    action: edit
    tagPattern: v\d+\.\d+(\.\d+)?-.*
    tag: $(TAG)
    assets: executable/target/executable-*.jar
    isPreRelease: true
    addChangeLog: false