trigger:
- master
- develop

variables:
- group: ConqueryConstants

pool:
  vmImage: $(IMAGE)
steps:
- task: Maven@3
  displayName: build conquery
  inputs:
    jdkVersionOption: '1.11'
    goals: install
    options: $(MVN) -T 1C -DskipTests -pl !frontend-resources,!executable
- task: Maven@3
  displayName: autodoc
  inputs:
    jdkVersionOption: '1.11'
    goals: exec:java
    options: $(MVN) -Dexec.mainClass="com.bakdata.conquery.AutoDoc" -pl autodoc
- bash: |
    git diff --quiet HEAD || \
    {
      git commit --message "automatic update to docs"
      git push origin HEAD:$(Build.SourceBranch)
      exit -1
    }