sudo: required
language: java
services:
  - docker
deploy:
  provider: releases
  api_key: 486ee03d9030fae114c0a8598b58c04963c6efea
  file_glob: true
  file: frontend/cfp-*.tgz
  skip_cleanup: true
  on:
    tags: true
