sudo: required
language: java
cache:
  directories:
  - $HOME/.m2
services:
  - docker
deploy:
  # Deploy the file(s) to the github release (other targets like amazon-aws or npm can be found here: http://docs.travis-ci.com/user/deployment/ )
  provider: releases
  # The oauth token for github (used by travis to upload the file(s) to github)
  api_key:
    # The api-key is encrypted like described here: http://docs.travis-ci.com/user/encryption-keys/  (only travis can decrypt the key)
    secure: "JGH1j6oJrZTUk6PlJXgEz8KKSjhl/r90Q7fz2fUwxc8cQh+Ef0jcfzfXicOoRnIoLc8IjSXE5Kr+rS+FnsMgvkZ0Zl8MJF6V7Y383I7n+wK9BYk14n6YwxoIHoxpnxpBoQXIAuEjJUaWQpWTJuWy78BU5TEF125muUpHGhS/zUfuTp0MBblNuIETAsle/jLRbPB0pbCQiMXbM2dioalor3PUAoSi49r1C3vugHsG7nuVj8vfYexsmHaryMXgK1hoXC/uB+b0eTKHtXn3Uo0MaWUFdaI05GaT/miNFKxwVEGgf9NDEyyZHd9Z5ecoB1uUkatMZM6vGRaLk5Ge1JEIyss4vSvPLnXzxuWqWZKYCiGh481kHNbQvAx3GXwrkPRB9ZCoKAom/M61qL4Xcj+JRPWeuRiyiXxldvSQyiSP+JVsViB93uvXs682Zskh23UPR1N98fUL/RgnwtVU1CGVUo+sxPoCxnHmo4/x4GkDQofi7vVvhyxHe/jhdPg3WSiLlPoCmAZy58knaygBI4pWoT92RfHatFVVT4/CpgYqjKorHHSPsYXr+Jb56h8mD4pI2kQ7zPBhmZw4FBzVujkPc6eLDNbtqVjwlo5c2MEks+/svEoDafvydbX24A4qqr/2WkLuC5Iw3f2LF+8M4yLah59z5CX7Gogc4ym5vErhEF0="
  # enable wildcards
  file_glob: true
  # Which file(s) to upload
  file: frontend/cfp-*.tgz
  # do not delete the files we're trying to upload
  skip_cleanup: true
  # only deploy if
  on:
    # we are on this repo
    repo: bakdata/conquery
    # and we are building a tag
    tags: true
