sudo: required
language: java
services:
  - docker
deploy:
  provider: releases
  api_key: ${GITHUB_DEPLOY_TOKEN}
  file_glob: true
  file: frontend/cfp-*.tgz
  skip_cleanup: true
  on:
    tags: true
