language: java
os:
  - linux

jdk:
  - openjdk11

jobs:
  include:
    - stage: "Tests"

      name: "Unit Tests"
      script: mvn test -B -DskipDockerTests=true -DexcludedGroups="INTEGRATION_PROGRAMMATIC, INTEGRATION_JSON"

    - name: "Programmatic Integration Tests"
      script: mvn test -B -DskipDockerTests=true -Dgroups="INTEGRATION_PROGRAMMATIC"

    - name: "Integration Tests"
      script: mvn test -B -DskipDockerTests=true -Dgroups="INTEGRATION_JSON"
  
cache:
  directories:
    - "$HOME/.cache"
    - "$HOME/.m2"

deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x frontend/scripts/deploy-npm.sh && sh frontend/scripts/deploy-npm.sh
    on:
      tags: true
  - provider: script
    script: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh && bash frontend/scripts/deploy-heroku-docker.sh conquery-dev
    on:
      branch: develop
  - provider: script
    script: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh && bash frontend/scripts/deploy-heroku-docker.sh conquery
    on:
      branch: master
