trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: mvn -B -V -T 1C install -N
  displayName: build root
- script: mvn -B -V install -pl frontend-resources
  displayName: test frontend
- script: mvn -B -V -T 1C install -pl backend -DexcludedGroups="INTEGRATION_PROGRAMMATIC, INTEGRATION_JSON"
  displayName: unit tests
- script: mvn -B -V -T 1C test -pl backend -Dgroups="INTEGRATION_PROGRAMMATIC"
  displayName: programmatic integration tests
- script: mvn -B -V -T 1C test -pl backend -Dgroups="INTEGRATION_JSON"
  displayName: json integration tests
