name: "OpenAPI linter"
on:
  pull_request:
    paths:
      - "openapi.yaml"
      - ".github/workflows/lint_openapi.yaml"

jobs:
  release:
    runs-on: ubuntu-latest
    container: dshanley/vacuum

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Lint OpenApi spec"
        run: vacuum lint --details openapi.yaml
