name: "Reintegrate master"

on:
  push:
    branches:
      - test/master

jobs:
  bump-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: test/master
          base: test/develop
          title: Reintegrate Master
          assignees: awildturtok,thoniTUB
          reviewers: awildturtok,thoniTUB
