name: "Reintegrate master"

on:
  push:
    branches:
      - master

jobs:
  bump-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          branch: master
          base: develop
          title: Reintegrate Master
          assignees: awildturtok,thoniTUB
          reviewers: awildturtok,thoniTUB