name: "AutoDoc"

on:
  pull_request:
    paths:
      - "autodoc/**"
      - "backend/src/main/java/com/bakdata/conquery/models/dataset/**"
      - "backend/src/main/java/com/bakdata/conquery/models/config/**"
      - "backend/src/main/java/com/bakdata/conquery/preproc/**"
      - "backend/src/main/java/com/bakdata/conquery/resources/**"
      - "backend/src/main/java/com/bakdata/conquery/apiv1/**"
      - ".github/workflows/run_autodoc.yml" # self reference

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Backend
        run: mvn -T 1C install -pl backend -DskipTests
      - name: Build AutoDoc
        run: mvn exec:java -f autodoc/pom.xml -Dexec.mainClass="com.bakdata.conquery.AutoDoc" -Dexec.arguments=docs
      - name: push new docs
        run: |
            echo "Diffing the generated docs with the previous state"

            if git diff --quiet HEAD
            then
              echo "No changes detected"
              exit 0
            fi

            echo "Documentation needs update"
            git config --global user.email "bot@bakdata.com"
            git config --global user.name "bakdata-bot"
            git add docs/*
            git commit --message "automatic update to docs"
            git push || exit 1
            echo "Documentation updated"

            exit 0