name: "AutoDoc"

on:
  pull_request:
    paths:
      - "autodoc/**"
      - "backend/src/main/java/com/bakdata/conquery/models/dataset/**"
      - "backend/src/main/java/com/bakdata/conquery/models/config/**"
      - "backend/src/main/java/com/bakdata/conquery/preproc/**"
      - "backend/src/main/java/com/bakdata/conquery/resources/**"
      - "backend/src/main/java/com/bakdata/conquery/apiv1/**"
      - ".github/workflows/run_autodoc.yml" # self reference

jobs:
  generate_auto_doc:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Backend
        run: mvn install -T 1C -DskipTests -pl '!executable'
      - name: Run AutoDoc
        run: mvn exec:java -f autodoc/pom.xml -Dexec.mainClass="com.bakdata.conquery.AutoDoc" -Dexec.arguments=docs
      - name: Check for changes
        id: check-changes
        run: |
          changes=$(git diff-index HEAD)
          echo $changes
          echo "::set-output name=changed::$(if [[ ${changes} ]]; then echo true; else echo false; fi)"
      - name: Commit files
        id: commit-files
        if: ${{ steps.check-changes.outputs.changed }}
        run: |
          echo ${{ env.GITHUB_REF }}
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update AutoDoc" -a
      - name: Push changes
        if: ${{ steps.commit-files.conclusion == 'success' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}